# Generated by Django 4.0.4 on 2022-05-27 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='preable',
            new_name='preambule',
        ),
    ]
