# Generated by Django 4.0.4 on 2022-05-30 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_preable_news_preambule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-created',), 'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
    ]
